import { PrismaClient } from '@prisma/client';
import { createId } from '@paralleldrive/cuid2';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Iniciando seed...');

  await prisma.order_items.deleteMany();
  await prisma.orders.deleteMany();
  await prisma.product_reviews.deleteMany();
  await prisma.products.deleteMany();
  await prisma.categories.deleteMany();
  await prisma.user.deleteMany();

  const [ninas, ninos, bebes] = await Promise.all([
    prisma.categories.create({ data: { id: createId(), name: 'Ropa de Niñas', description: 'Vestidos, conjuntos y accesorios para niñas de 2 a 12 años', imageUrl: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800', icon: '👗', updatedAt: new Date() }}),
    prisma.categories.create({ data: { id: createId(), name: 'Ropa de Niños', description: 'Remeras, pantalones y buzos para niños de 2 a 12 años', imageUrl: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800', icon: '👕', updatedAt: new Date() }}),
    prisma.categories.create({ data: { id: createId(), name: 'Ropa de Bebés', description: 'Bodies, enteritos y conjuntos para bebés de 0 a 24 meses', imageUrl: 'https://images.unsplash.com/photo-1519689373023-dd07c7988603?w=800', icon: '👶', updatedAt: new Date() }})
  ]);

  const products = [
    // NIÑAS
    { id: createId(), name: 'Vestido Floral Rosa', description: 'Hermoso vestido con estampado de flores, confeccionado en algodón 100%. Ideal para eventos especiales o uso diario. Incluye lazo ajustable en la cintura.', price: 8500, salePrice: 6800, stock: 25, onSale: true, categoryId: ninas.id, images: '["https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800","https://images.unsplash.com/photo-1621452773781-0f992fd1f5cb?w=800","https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=800"]', colors: ['Rosa','Celeste','Blanco'], sizes: ['4','6','8','10','12'], features: ['100% algodón premium','Estampado floral resistente','Lavable en lavarropas','Lazo ajustable en cintura','Forro interior suave'], rating: 4.8, reviewCount: 42, weight: 180, height: 2, width: 25, length: 35, updatedAt: new Date() },
    { id: createId(), name: 'Conjunto Deportivo Rosa', description: 'Conjunto deportivo de 2 piezas: buzo con capucha y pantalón jogger. Confeccionado en tela francesa de primera calidad, ideal para el día a día.', price: 7200, stock: 18, categoryId: ninas.id, images: '["https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800","https://images.unsplash.com/photo-1582552938357-32b906d8788f?w=800"]', colors: ['Rosa','Gris','Negro'], sizes: ['4','6','8','10'], features: ['Tela deportiva respirable','Capucha con cordón','Bolsillos laterales','Puños y ruedo con elastano'], rating: 4.6, reviewCount: 28, weight: 320, height: 3, width: 28, length: 38, updatedAt: new Date() },
    { id: createId(), name: 'Remera Unicornio con Lentejuelas', description: 'Remera mágica con diseño de unicornio en lentejuelas reversibles. Al pasar la mano cambia de color. Confeccionada en algodón suave.', price: 4800, salePrice: 3600, stock: 35, onSale: true, categoryId: ninas.id, images: '["https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=800"]', colors: ['Blanco','Rosa','Celeste'], sizes: ['2','4','6','8','10'], features: ['Lentejuelas reversibles mágicas','100% algodón','Diseño de unicornio','Cuello redondo reforzado'], rating: 4.9, reviewCount: 67, weight: 120, height: 1, width: 22, length: 28, updatedAt: new Date() },
    { id: createId(), name: 'Jean Skinny Celeste', description: 'Jean elastizado de corte skinny, cómodo y moderno. Tela denim con elastano para mayor movilidad. Cinco bolsillos y cierre con botón.', price: 6900, stock: 22, categoryId: ninas.id, images: '["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800"]', colors: ['Celeste','Azul','Negro'], sizes: ['6','8','10','12','14'], features: ['Denim stretch premium','Corte skinny moderno','5 bolsillos funcionales','Cierre con botón metálico'], rating: 4.7, reviewCount: 31, weight: 280, height: 2, width: 26, length: 32, updatedAt: new Date() },
    { id: createId(), name: 'Campera Acolchada con Capucha', description: 'Campera ultraliviana con relleno sintético de alta calidad. Repelente al agua, con capucha desmontable y bolsillos con cierre. Ideal para entretiempo.', price: 12500, stock: 15, categoryId: ninas.id, images: '["https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800","https://images.unsplash.com/photo-1544923408-75c5cef46f14?w=800"]', colors: ['Rosa','Azul marino','Negro'], sizes: ['6','8','10','12'], features: ['Ultraliviana y abrigada','Capucha desmontable','Repelente al agua','Bolsillos con cierre','Relleno sintético hipoalergénico'], rating: 4.8, reviewCount: 19, weight: 380, height: 5, width: 32, length: 42, updatedAt: new Date() },
    // NIÑOS
    { id: createId(), name: 'Remera Selección Argentina', description: 'Remera deportiva con los colores de la Selección Argentina. Tela deportiva de secado rápido, perfecta para jugar al fútbol o uso diario.', price: 4500, stock: 38, categoryId: ninos.id, images: '["https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800"]', colors: ['Celeste y blanco','Azul marino'], sizes: ['4','6','8','10','12','14'], features: ['Tela deportiva respirable','Secado rápido','Colores selección argentina','Cuello reforzado'], rating: 4.8, reviewCount: 94, weight: 130, height: 1, width: 24, length: 30, updatedAt: new Date() },
    { id: createId(), name: 'Conjunto Deportivo Nike Style', description: 'Conjunto deportivo inspirado en las grandes marcas: buzo canguro con capucha y pantalón jogger. Tela francesa de primera calidad con interior afelpado.', price: 8900, salePrice: 7120, stock: 16, onSale: true, categoryId: ninos.id, images: '["https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800"]', colors: ['Negro','Azul marino','Gris'], sizes: ['6','8','10','12','14'], features: ['Tela francesa afelpada','Buzo tipo canguro','Pantalón con bolsillos','Puños y ruedo elastizados'], rating: 4.7, reviewCount: 45, weight: 420, height: 4, width: 30, length: 38, updatedAt: new Date() },
    { id: createId(), name: 'Jean Recto Clásico Azul', description: 'Jean clásico de corte recto, cinco bolsillos funcionales. Denim de alta resistencia, ideal para el uso diario y el colegio.', price: 7200, stock: 25, categoryId: ninos.id, images: '["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800"]', colors: ['Azul','Negro','Gris'], sizes: ['6','8','10','12','14','16'], features: ['Denim resistente','Corte recto clásico','5 bolsillos','Cierre con botón'], rating: 4.6, reviewCount: 38, weight: 320, height: 2, width: 28, length: 34, updatedAt: new Date() },
    { id: createId(), name: 'Buzo Canguro Gamer', description: 'Buzo con capucha y diseño gamer, perfecto para los fanáticos de los videojuegos. Tela francesa afelpada súper cómoda, con bolsillo tipo canguro.', price: 6800, stock: 22, categoryId: ninos.id, images: '["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]', colors: ['Negro','Gris oscuro','Azul'], sizes: ['8','10','12','14'], features: ['Diseño gamer exclusivo','Tela francesa afelpada','Capucha con cordón','Bolsillo canguro grande'], rating: 4.9, reviewCount: 67, weight: 380, height: 3, width: 30, length: 36, updatedAt: new Date() },
    { id: createId(), name: 'Bermuda Cargo con Bolsillos', description: 'Bermuda de gabardina con múltiples bolsillos cargo. Ideal para el verano y actividades al aire libre. Cintura regulable con elástico interno.', price: 5400, stock: 30, categoryId: ninos.id, images: '["https://images.unsplash.com/photo-1598032895397-d5abbd161a07?w=800"]', colors: ['Beige','Verde militar','Azul'], sizes: ['6','8','10','12','14'], features: ['Gabardina resistente','Múltiples bolsillos cargo','Cintura regulable','Ideal para verano'], rating: 4.5, reviewCount: 29, weight: 240, height: 2, width: 26, length: 30, updatedAt: new Date() },
    // BEBÉS
    { id: createId(), name: 'Pack 3 Bodies de Algodón', description: 'Set de 3 bodies de algodón peinado extra suave. Broches en la entrepierna para facilitar el cambio de pañal. Perfectos para uso diario.', price: 6900, stock: 35, categoryId: bebes.id, images: '["https://images.unsplash.com/photo-1519689373023-dd07c7988603?w=800"]', colors: ['Blanco','Beige','Gris'], sizes: ['0-3 meses','3-6 meses','6-9 meses','9-12 meses'], features: ['Pack de 3 unidades','Algodón peinado 100%','Broches en entrepierna','Cuello elástico reforzado','Lavable a máquina'], rating: 4.9, reviewCount: 127, weight: 150, height: 1, width: 20, length: 25, updatedAt: new Date() },
    { id: createId(), name: 'Enterito Osito Polar', description: 'Enterito de polar súper suave con capucha de osito. Incluye piecitos cerrados y cierre frontal completo. Ideal para los días fríos.', price: 8500, salePrice: 6800, stock: 18, onSale: true, categoryId: bebes.id, images: '["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800"]', colors: ['Beige','Gris','Celeste'], sizes: ['0-3 meses','3-6 meses','6-9 meses'], features: ['Polar suave y abrigado','Capucha con orejas de osito','Piecitos cerrados','Cierre frontal completo'], rating: 5.0, reviewCount: 89, weight: 200, height: 2, width: 22, length: 28, updatedAt: new Date() },
    { id: createId(), name: 'Conjunto 3 Piezas Algodón', description: 'Set completo: body, pantalón y gorrito a juego. Confeccionado en algodón orgánico certificado, ideal para pieles sensibles.', price: 7800, stock: 24, categoryId: bebes.id, images: '["https://images.unsplash.com/photo-1522771930-78848d9293e8?w=800"]', colors: ['Blanco','Menta','Rosa suave'], sizes: ['0-3 meses','3-6 meses','6-9 meses'], features: ['Set de 3 piezas','Algodón orgánico certificado','Sin irritantes','Body con broches','Gorrito elástico'], rating: 4.8, reviewCount: 64, weight: 180, height: 2, width: 22, length: 26, updatedAt: new Date() },
    { id: createId(), name: 'Pijama 2 Piezas Estrellas', description: 'Pijama de dos piezas con estampado de estrellas. Remera de manga larga y pantalón con piecitos antideslizantes. Perfecto para dormir seguro.', price: 5600, stock: 28, categoryId: bebes.id, images: '["https://images.unsplash.com/photo-1519689373023-dd07c7988603?w=800"]', colors: ['Azul','Rosa','Gris'], sizes: ['6-9 meses','9-12 meses','12-18 meses'], features: ['Estampado de estrellas','Piecitos antideslizantes','Algodón suave','Elástico en cintura'], rating: 4.7, reviewCount: 43, weight: 170, height: 2, width: 22, length: 28, updatedAt: new Date() },
    { id: createId(), name: 'Manta Polar con Capucha', description: 'Manta de polar premium con capucha bordada. Tamaño 75x75cm, perfecta para abrigar al bebé en el cochecito o en casa. Súper suave y calientita.', price: 6400, salePrice: 5120, stock: 15, onSale: true, categoryId: bebes.id, images: '["https://images.unsplash.com/photo-1522771930-78848d9293e8?w=800"]', colors: ['Celeste','Rosa','Gris'], sizes: ['75x75 cm'], features: ['Polar premium súper suave','Capucha bordada','Tamaño 75x75cm','Ideal para cochecito','Lavable a máquina'], rating: 4.9, reviewCount: 52, weight: 320, height: 5, width: 25, length: 30, updatedAt: new Date() },
  ];

  await prisma.products.createMany({ data: products });
  await prisma.user.create({ data: { id: createId(), email: 'admin@rastuci.com', name: 'Admin', password: '$2b$10$L0ecUp38mrEEEw9LKISmDOHLWDjTYjMu7z2myubPVDYMhtkFUs8jO', isAdmin: true }});

  console.log('✅ Seed completado: 3 categorías, 15 productos, 1 admin (admin@rastuci.com / admin123)');
}

main()
  .catch((e) => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
